# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0b7ba07c3b612a3e7ec0a61cd794aa29"
name = "Dupli Products"
application_url = "https://dupli-app.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_inventory,read_inventory,read_locales,write_locales,write_locations,read_locations,read_products,write_products"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[pos]
embedded = true
